version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    platform: linux/x86_64
    volumes:
      - ./migration:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  db-data: