// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTimeTable struct {
	Ids []string `json:"ids"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
